import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Tailwind</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header></header>

      <main className="flex h-screen w-screen items-center justify-center bg-[#D15B64] text-white">
        <p>Coming soon</p>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
